export const STATUS_MAP = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const;

export const STATUS = [STATUS_MAP.PENDING, STATUS_MAP.APPROVED, STATUS_MAP.REJECTED] as const;
